### ISSUE TITLE
Nothing works...

### ISSUE THREAD

**Issue by demian85** [noffle/electron-speech#2]
This simple script raises the error: ReferenceError: webkitSpeechRecognition is not defined

```
var Speech = require('electron-speech')
var speech = Speech({continuous: true});
speech.pipe(process.stdout);

ReferenceError: webkitSpeechRecognition is not defined
    at new Speech (/usr/lib/node_modules/electron-speech/index.js:19:26)
    at Speech (/usr/lib/node_modules/electron-speech/index.js:12:43)
    at Object.<anonymous> (/home/demian/www/calendar-telegram-bot/test.js:21:14)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:141:18)
    at node.js:933:3
```

And electron-speech cmd also fails:

```
> electron-speech 
[16309:0304/152935:ERROR:browser_main_loop.cc(173)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
Error opening app
The app provided is not a valid electron app, please read the docs on how to write one:
https://github.com/atom/electron/tree/master/docs

Error: Cannot find module 'electron'
```

**Comment by hackergrrl** [comment]
Simple script: are you running this in the browser or with Node? If the latter, you'll need to install [electron-spawn](https://www.npmjs.com/package/electron-spawn) and run it with that. (i.e. `electron-spawn test.js`).

Command: you'll need to have `electron` on your machine. You can install this with `npm install -g electron-prebuilt`.

Thanks for the bug reports! I think these are both instances of documentation neglect that I'll rectify.

**Comment by hackergrrl** [comment]
I've added a [prerequisites](https://github.com/noffle/electron-speech#prerequisites) section to the REAMDE. Thanks!

**Comment by demian85** [comment]
Why is it necessary to install electron globally? It automatically installs as a dependency of electron-speech.

I'm interested in recognizing speech from an audio file anyway. This doesn't seem to help me. Do you know if the Chrome Speech API supports an audio stream as input?

**Comment by hackergrrl** [comment]
> Why is it necessary to install electron globally? It automatically installs as a dependency of electron-speech.

Agreed. I'm not sure how you ended up in the state of seeing `Error: Cannot find module 'electron'` though -- did you not install globally?
