### ISSUE TITLE
cloned and getting this error

### ISSUE THREAD

**Issue by TheGuy68** [noffle/electron-speech#6]
I have to say. Your module looks awesome. but im a little confused. 1 line says i need to run the app with electron-spawn and the other says electron-speech.
Its not clear to me how the project needs settings up etc from here.

I just cloned the repo and tried ele-spawn foo.js and executed with no errors. 
Then elec-speech and got the errors below.

Thank you

A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'app'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (/usr/lib/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/electron-speech/node_modules/electron-spawn/cli.js:4:11)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)

**Comment by hackergrrl** [comment]
Thanks for reporting! Pull down the latest -- fixed in 1.0.6.
